# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm' # For JavaScript/Node.js projects
    directory: '/' # Location of package.json
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      nestjs-dependencies:
        patterns:
          - '@nestjs/*'
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      # Ignore major updates to TypeScript as they may require manual migration
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
