# CodeRabbit Configuration
language: en-US
tone_instructions: '' # Example: 'Use a friendly, helpful tone'
early_access: true
enable_free_tier: true

reviews:
  profile: assertive # Options: chill, assertive
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: true

  # Labeling instructions
  labeling_instructions: []
  # Example:
  # - label: frontend
  #   instructions: Apply when the PR/MR contains changes to the react components.

  # Path filters and instructions
  path_filters: []
  path_instructions: []
  # Example:
  # - path: "**/*.ts"
  #   instructions: "Ensure TypeScript code follows conventions"

  abort_on_close: true
  disable_cache: false

  # Auto review settings
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: true
    base_branches: []

  # Finishing touches
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  # Tools integration
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []

    shellcheck:
      enabled: true

    ruff:
      enabled: true

    markdownlint:
      enabled: true

    github-checks:
      enabled: true
      timeout_ms: 90000

    languagetool:
      enabled: true
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default # Options: default, picky

    biome:
      enabled: true

    hadolint:
      enabled: true

    swiftlint:
      enabled: true
      config_file: ''

    phpstan:
      enabled: true
      level: default

    golangci-lint:
      enabled: true
      config_file: ''

    yamllint:
      enabled: true

    gitleaks:
      enabled: true

    checkov:
      enabled: true

    detekt:
      enabled: true
      config_file: ''

    eslint:
      enabled: true

    rubocop:
      enabled: true

    buf:
      enabled: true

    regal:
      enabled: true

    actionlint:
      enabled: true

    pmd:
      enabled: true
      config_file: ''

    cppcheck:
      enabled: true

    semgrep:
      enabled: true
      config_file: ''

    circleci:
      enabled: true

    sqlfluff:
      enabled: true

    prismaLint:
      enabled: true

    oxc:
      enabled: true

    shopifyThemeCheck:
      enabled: true

# Chat configuration
chat:
  auto_reply: true
  integrations:
    jira:
      usage: auto # Options: auto, enabled, disabled
    linear:
      usage: auto # Options: auto, enabled, disabled

# Knowledge base configuration
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: auto # Options: local, global, auto
  issues:
    scope: auto # Options: local, global, auto
  jira:
    usage: auto # Options: auto, enabled, disabled
    project_keys: []
  linear:
    usage: auto # Options: auto, enabled, disabled
    team_keys: []
  pull_requests:
    scope: auto # Options: local, global, auto

# Code generation configuration
code_generation:
  docstrings:
    language: en-US
    path_instructions: []
    # Example:
    # - path: "**/*.ts"
    #   instructions: "Follow TSDoc style for TypeScript files"
  unit_tests:
    path_instructions: []
    # Example:
    # - path: "**/*.ts"
    #   instructions: "Use Jest for TypeScript unit tests"
